# D\u00F9ng H2 mode MySQL \u0111\u1EC3 n\u00F3 hi\u1EC3u \u0111\u01B0\u1EE3c c\u00E1c c\u00FA ph\u00E1p \u0111\u1EB7c th\u00F9 c\u1EE7a MySQL
spring.datasource.url=jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# T\u1EF1 \u0111\u1ED9ng t\u1EA1o b\u1EA3ng t\u1EEB Entity
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true